### ISSUE TITLE
how deploy in ubuntu azure instance?

### ISSUE THREAD

**Issue by johnfelipe** [Tirth27/Detecting-diabetic-retinopathy#4]

**Comment by Tirth27** [comment]
Hi @johnfelipe,

Could you please provide further detail about what have you tried so far and what you wanted to achieve. So I can understand what you need.

**Comment by YUN-XIAO-MO** [comment]
respected sir，I come from gregwchase/eyenet  ---2018, I saw your message in the issue.May I ask how you solve the question that the file X_train_256_v2.npy can't be build?
